# Generated by Django 5.0.1 on 2024-02-10 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_dislikes_comentario_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='estrelas',
            field=models.FloatField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
