# Generated by Django 5.0.1 on 2024-02-12 23:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_comentario_estrelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='estrelas',
            field=models.FloatField(blank=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
