# Generated by Django 5.0.1 on 2024-02-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0005_remove_comentario_estrelas_estrela'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estrela',
        ),
    ]
