# Generated by Django 5.0.1 on 2024-02-13 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_estrela_avaliacao_estrelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='estrelas',
        ),
        migrations.AddField(
            model_name='estrela',
            name='avaliacao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='estrelas', to='avaliacoes.avaliacao'),
            preserve_default=False,
        ),
    ]
