# Generated by Django 5.0.1 on 2024-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_rename_user_estrela_usuario_remove_estrela_avaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='estrelas',
        ),
        migrations.AddField(
            model_name='estrela',
            name='avaliacoes',
            field=models.ManyToManyField(related_name='estrelas', to='avaliacoes.avaliacao'),
        ),
    ]
